name: Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "eslint.config.js"
      - "vitest.config.mts"
      - ".github/workflows/test.yml"
    branches: [main, master]
  push:
    paths:
      - "src/**"
      - "test/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - "eslint.config.js"
      - "vitest.config.mts"
      - ".github/workflows/test.yml"
    branches: [main, master]

jobs:
  tests:
    if: github.repository == 'raycast/utils'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: raycast/github-actions/git-checkout@v1.13.0
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22.22.2
      - name: Npm Install
        run: npm ci
      - name: Npm Lint
        run: npm run test
      - name: Build
        run: npm run build
      - name: Npm Install Tests
        run: npm ci
        working-directory: ./smoke-tests
      - name: Build tests
        run: npm run build
        working-directory: ./smoke-tests
